---
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - pandoc
      - libxml2-utils
      - devscripts
      - build-essential
      - lintian
      - debhelper

script:
  - make test
  - ./mdcheckr README.md

